module.exports = function () {

    return horses = [
        {color: 'White', mane: 'White', tail: 'White', shoes: 'White', eye: 'White', unicorn: 'White', wings: 'White'},
        {color: 'DimGrey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Grey'},
        {color: 'Lavender', mane: 'Purple', tail: 'Purple', shoes: 'Indigo', eye: 'Pink', unicorn: 'Gold', wings: 'GoldenRod'},
        {color: 'DarkBlue', mane: 'DarkSlateGrey', tail: 'DarkSlateGrey', shoes: 'Black', eye: 'Blue', wings: 'Yellow'},
        {color: 'Coral', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Purple', mane: 'Gold', tail: 'Gold', shoes: 'Black', eye: 'Orange', unicorn: 'GoldenRod', wings: 'GoldenRod'}, // KJC
        {color: 'Orange', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'} , // ABC
        {color: 'DarkCyan', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'GoldenRod'} , // AMC
        {color: 'DeepPink', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'} , // S
        {color: 'AliceBlue ', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'} , // K
        {color: 'CornSilk', mane: 'Grey', tail: 'Grey', shoes: 'Grey', eye: 'Pink', unicorn: 'GoldenRod'} , // SF 
        {color: 'Azure', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'} , // X
        {color: 'Ivory', mane: 'DarkViolet', tail: 'DarkViolet', shoes: 'Black', eye: 'Pink'} , // T
        {color: 'Indigo', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},  // A
        {color: 'AntiqueWhite', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Aqua', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Aquamarine', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Beige', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Bisque', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'BlanchedAlmond', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Blue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'BlueViolet', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Brown', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'BurlyWood', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'CadetBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Chartreuse', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Chocolate', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'CornflowerBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Crimson', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Cyan', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkCyan', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkGoldenRod', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Brown', mane: 'Gold', tail: 'Green', shoes: 'Black', eye: 'Red'},
        {color: 'Aquamarine', mane: 'CornSilk', tail: 'CornSilk', shoes: 'GoldenRod', eye: 'Grey', unicorn: 'GoldenRod', wings: 'GoldenRod'},
        {color: 'AliceBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Pink', mane: 'DeepPink', tail: 'DeepPink', shoes: 'PaleVioletRed', eye: 'MediumSlateBlue', unicorn: 'HotPink', wings: 'MediumVioletRed'},
        {color: 'Black', mane: 'DimGrey', tail: 'DimGrey', shoes: 'DimGrey', eye: 'Yellow'},
        {color: 'DarkGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkGrey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'GoldenRod'},
        {color: 'DarkKhaki', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkMagenta', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkOliveGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkOrange', mane: 'Brown', tail: 'Brown', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkOrchid', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkRed', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkSalmon', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkSeaGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkSlateBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkSlateGrey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkTurquoise', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DarkViolet', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DeepPink', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DeepSkyBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DimGrey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'DodgerBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', wings: 'GoldenRod'},
        {color: 'FireBrick', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'FloralWhite', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'ForestGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Fuchsia', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Gainsboro', mane: 'GoldenRod', tail: 'GoldenRod', shoes: 'Black', eye: 'Pink'},
        {color: 'GhostWhite', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Gold', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'GoldenRod', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'Gold'},
        {color: 'Green', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'GreenYellow', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Grey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'HoneyDew', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'HotPink', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'IndianRed', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Indigo', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Ivory', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Khaki', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Lavender', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LavenderBlush', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LawnGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LemonChiffon', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LightBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LightCoral', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LightCyan', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LightGoldenRodYellow', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LightGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LightGrey', mane: 'Black', tail: 'Black', shoes: 'Grey', eye: 'Pink'},
        {color: 'LightPink', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LightSalmon', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LightSeaGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LightSkyBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LightSlateGrey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LightSteelBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', wings: 'GoldenRod'},
        {color: 'LightYellow', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Lime', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'LimeGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Linen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Magenta', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Maroon', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'MediumAquaMarine', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'MediumBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'MediumOrchid', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'MediumPurple', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'MediumSeaGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'MediumSlateBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'MediumSpringGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'MediumTurquoise', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'MediumVioletRed', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'Gold'},
        {color: 'MidnightBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'MintCream', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'MistyRose', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Moccasin', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'NavajoWhite', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Navy', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'OldLace', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Olive', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'OliveDrab', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'Gold'},
        {color: 'OrangeRed', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Orchid', mane: 'PowderBlue', tail: 'PowderBlue', shoes: 'Black', eye: 'Pink'},
        {color: 'PaleGoldenRod', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'PaleGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'PaleTurquoise', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'PaleVioletRed', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'PapayaWhip', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'PaleTurquoise'},
        {color: 'PeachPuff', mane: 'SaddleBrown', tail: 'SaddleBrown', shoes: 'Black', eye: 'Pink'},
        {color: 'Peru', mane: 'SaddleBrown', tail: 'SaddleBrown', shoes: 'Black', eye: 'Pink'},
        {color: 'Plum', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'PowderBlue', mane: 'SkyBlue', tail: 'SkyBlue', shoes: 'Black', eye: 'Pink', wings: 'GoldenRod'},
        {color: 'Purple', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'RebeccaPurple', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Red', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'RosyBrown', mane: 'SaddleBrown', tail: 'SaddleBrown', shoes: 'Black', eye: 'Pink'},
        {color: 'RoyalBlue', mane: 'Black', tail: 'Black', shoes: 'PowderBlue', eye: 'Pink'},
        {color: 'SaddleBrown', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Salmon', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'SandyBrown', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Yellow'},
        {color: 'SeaGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'SeaShell', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Sienna', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Silver', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', wings: 'Black'},
        {color: 'SkyBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'SlateBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'SlateGrey', mane: 'DarkSlateBlue', tail: 'DarkSlateBlue', shoes: 'Black', eye: 'Pink', wings: 'GoldenRod'},
        {color: 'Snow', mane: 'SteelBlue', tail: 'SteelBlue', shoes: 'Black', eye: 'Pink'},
        {color: 'SpringGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'SteelBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Tan', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Teal', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Thistle', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'Gold'},
        {color: 'Tomato', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Turquoise', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Violet', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Wheat', mane: 'SteelBlue', tail: 'SteelBlue', shoes: 'Black', eye: 'Pink'},
        {color: 'WhiteSmoke', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'Yellow', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'},
        {color: 'YellowGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink'}        
    ]
}