module.exports = function () {

    return horses = [
        { color: 'White', mane: 'White', tail: 'White', shoes: 'White', eye: 'White', unicorn: 'White', wings: 'White' },
        { color: 'DimGrey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Grey' },
        { color: 'Lavender', mane: 'Purple', tail: 'Purple', shoes: 'Indigo', eye: 'Pink', unicorn: 'Gold', wings: 'GoldenRod' },
        { color: 'DarkBlue', mane: 'DarkSlateGrey', tail: 'DarkSlateGrey', shoes: 'Black', eye: 'Blue', wings: 'Yellow' },
        { color: 'Coral', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Purple', mane: 'Gold', tail: 'Gold', shoes: 'Black', eye: 'Orange', unicorn: 'GoldenRod', wings: 'GoldenRod' }, // KJC
        { color: 'Orange', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' }, // ABC
        { color: 'DarkCyan', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'GoldenRod' }, // AMC
        { color: 'DeepPink', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' }, // S
        { color: 'AliceBlue ', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' }, // K
        { color: 'CornSilk', mane: 'Grey', tail: 'Grey', shoes: 'Grey', eye: 'Pink', unicorn: 'GoldenRod' }, // SF 
        { color: 'Azure', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' }, // X
        { color: 'Ivory', mane: 'DarkViolet', tail: 'DarkViolet', shoes: 'Black', eye: 'Pink' }, // T
        { color: 'Indigo', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },  // A
        { color: 'AntiqueWhite', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Aqua', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Aquamarine', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Beige', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Bisque', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'BlanchedAlmond', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Blue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'BlueViolet', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Brown', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'BurlyWood', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'CadetBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Chartreuse', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Chocolate', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'CornflowerBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Crimson', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Cyan', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkCyan', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkGoldenRod', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Brown', mane: 'Gold', tail: 'Green', shoes: 'Black', eye: 'Red' },
        { color: 'Aquamarine', mane: 'CornSilk', tail: 'CornSilk', shoes: 'GoldenRod', eye: 'Grey', unicorn: 'GoldenRod', wings: 'GoldenRod' },
        { color: 'AliceBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Pink', mane: 'DeepPink', tail: 'DeepPink', shoes: 'PaleVioletRed', eye: 'MediumSlateBlue', unicorn: 'HotPink', wings: 'MediumVioletRed' },
        { color: 'Black', mane: 'DimGrey', tail: 'DimGrey', shoes: 'DimGrey', eye: 'Yellow' },
        { color: 'DarkGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkGrey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'GoldenRod' },
        { color: 'DarkKhaki', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkMagenta', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkOliveGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkOrange', mane: 'Brown', tail: 'Brown', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkOrchid', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkRed', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkSalmon', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkSeaGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkSlateBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkSlateGrey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkTurquoise', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkViolet', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DeepPink', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DeepSkyBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DimGrey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DodgerBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', wings: 'GoldenRod' },
        { color: 'FireBrick', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'FloralWhite', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'ForestGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Fuchsia', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Gainsboro', mane: 'GoldenRod', tail: 'GoldenRod', shoes: 'Black', eye: 'Pink' },
        { color: 'GhostWhite', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Gold', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'GoldenRod', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'Gold' },
        { color: 'Green', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'GreenYellow', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Grey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'HoneyDew', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'HotPink', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'IndianRed', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Indigo', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Ivory', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Khaki', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Lavender', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LavenderBlush', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LawnGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LemonChiffon', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LightBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LightCoral', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LightCyan', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LightGoldenRodYellow', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LightGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LightGrey', mane: 'Black', tail: 'Black', shoes: 'Grey', eye: 'Pink' },
        { color: 'LightPink', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LightSalmon', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LightSeaGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LightSkyBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LightSlateGrey', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LightSteelBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', wings: 'GoldenRod' },
        { color: 'LightYellow', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Lime', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'LimeGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Linen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Magenta', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Maroon', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'MediumAquaMarine', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'MediumBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'MediumOrchid', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'MediumPurple', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'MediumSeaGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'MediumSlateBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'MediumSpringGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'MediumTurquoise', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'MediumVioletRed', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'Gold' },
        { color: 'MidnightBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'MintCream', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'MistyRose', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Moccasin', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'NavajoWhite', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Navy', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'OldLace', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Olive', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'OliveDrab', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'Gold' },
        { color: 'OrangeRed', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Orchid', mane: 'PowderBlue', tail: 'PowderBlue', shoes: 'Black', eye: 'Pink' },
        { color: 'PaleGoldenRod', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'PaleGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'PaleTurquoise', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'PaleVioletRed', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'PapayaWhip', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'PaleTurquoise' },
        { color: 'PeachPuff', mane: 'SaddleBrown', tail: 'SaddleBrown', shoes: 'Black', eye: 'Pink' },
        { color: 'Peru', mane: 'SaddleBrown', tail: 'SaddleBrown', shoes: 'Black', eye: 'Pink' },
        { color: 'Plum', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'PowderBlue', mane: 'SkyBlue', tail: 'SkyBlue', shoes: 'Black', eye: 'Pink', wings: 'GoldenRod' },
        { color: 'Purple', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'RebeccaPurple', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Red', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'RosyBrown', mane: 'SaddleBrown', tail: 'SaddleBrown', shoes: 'Black', eye: 'Pink' },
        { color: 'RoyalBlue', mane: 'Black', tail: 'Black', shoes: 'PowderBlue', eye: 'Pink' },
        { color: 'SaddleBrown', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Salmon', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'SandyBrown', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Yellow' },
        { color: 'SeaGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'SeaShell', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Sienna', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Silver', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', wings: 'Black' },
        { color: 'SkyBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'SlateBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'SlateGrey', mane: 'DarkSlateBlue', tail: 'DarkSlateBlue', shoes: 'Black', eye: 'Pink', wings: 'GoldenRod' },
        { color: 'Snow', mane: 'SteelBlue', tail: 'SteelBlue', shoes: 'Black', eye: 'Pink' },
        { color: 'SpringGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'SteelBlue', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Tan', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Teal', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Thistle', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink', unicorn: 'Gold' },
        { color: 'Tomato', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Turquoise', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Violet', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Wheat', mane: 'SteelBlue', tail: 'SteelBlue', shoes: 'Black', eye: 'Pink' },
        { color: 'WhiteSmoke', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'Yellow', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'YellowGreen', mane: 'Black', tail: 'Black', shoes: 'Black', eye: 'Pink' },
        { color: 'DarkGray', mane: 'AliceBlue', tail: 'AliceBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine', unicorn: 'Pink' },
        { color: 'DarkOliveGreen', mane: 'AntiqueWhite', tail: 'AntiqueWhite', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'PaleVioletRed', mane: 'Aqua', tail: 'Aqua', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Cornsilk', mane: 'Aquamarine', tail: 'Aquamarine', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Salmon', mane: 'Azure', tail: 'Azure', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'NavajoWhite', mane: 'Beige', tail: 'Beige', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Peru', mane: 'Bisque', tail: 'Bisque', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Ivory', mane: 'Black', tail: 'Black', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'MediumOrchid', mane: 'BlanchedAlmond', tail: 'BlanchedAlmond', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Cyan', mane: 'Blue', tail: 'Blue', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'LightCyan', mane: 'BlueViolet', tail: 'BlueViolet', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Wheat', mane: 'Brown', tail: 'Brown', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Aqua', mane: 'BurlyWood', tail: 'BurlyWood', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Black', mane: 'CadetBlue', tail: 'CadetBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Magenta', mane: 'Chartreuse', tail: 'Chartreuse', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'GoldenRod', mane: 'Chocolate', tail: 'Chocolate', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkSlateGray', mane: 'Coral', tail: 'Coral', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'IndianRed', mane: 'CornflowerBlue', tail: 'CornflowerBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine', wings: 'GoldenRod' },
        { color: 'BlueViolet', mane: 'Cornsilk', tail: 'Cornsilk', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Gold', mane: 'Crimson', tail: 'Crimson', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DimGray', mane: 'Cyan', tail: 'Cyan', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'MediumTurquoise', mane: 'DarkBlue', tail: 'DarkBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Blue', mane: 'DarkCyan', tail: 'DarkCyan', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'ForestGreen', mane: 'DarkGray', tail: 'DarkGray', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'SkyBlue', mane: 'DarkGray', tail: 'DarkGray', shoes: 'DarkSlateGrey', eye: 'Aquamarine', unicorn: 'GoldenRod', wings: 'GoldenRod' },
        { color: 'RebeccaPurple', mane: 'DarkGrey', tail: 'DarkGrey', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DeepSkyBlue', mane: 'DarkKhaki', tail: 'DarkKhaki', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'CornflowerBlue', mane: 'DarkMagenta', tail: 'DarkMagenta', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'MediumAquaMarine', mane: 'DarkOliveGreen', tail: 'DarkOliveGreen', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'MediumVioletRed', mane: 'DarkOrange', tail: 'DarkOrange', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkMagenta', mane: 'DarkOrchid', tail: 'DarkOrchid', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'LightPink', mane: 'DarkRed', tail: 'DarkRed', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'MidnightBlue', mane: 'DarkSalmon', tail: 'DarkSalmon', shoes: 'DarkSlateGrey', eye: 'Aquamarine', unicorn: 'GoldenRod' },
        { color: 'Turquoise', mane: 'DarkSeaGreen', tail: 'DarkSeaGreen', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkRed', mane: 'DarkSlateBlue', tail: 'DarkSlateBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'LightGoldenRodYellow', mane: 'DarkSlateGray', tail: 'DarkSlateGray', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Sienna', mane: 'DarkSlateGrey', tail: 'DarkSlateGrey', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Green', mane: 'DarkTurquoise', tail: 'DarkTurquoise', shoes: 'DarkSlateGrey', eye: 'DarkBlue' },
        { color: 'DimGrey', mane: 'DarkViolet', tail: 'DarkViolet', shoes: 'DarkSlateGrey', eye: 'Aquamarine', unicorn: 'GoldenRod' },
        { color: 'Pink', mane: 'DeepPink', tail: 'DeepPink', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Grey', mane: 'DeepSkyBlue', tail: 'DeepSkyBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Gainsboro', mane: 'DimGray', tail: 'DimGray', shoes: 'DarkSlateGrey', eye: 'Aquamarine' , unicorn: 'GoldenRod' },
        { color: 'Coral', mane: 'DimGrey', tail: 'DimGrey', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkCyan', mane: 'DodgerBlue', tail: 'DodgerBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Indigo', mane: 'ForestGreen', tail: 'ForestGreen', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Red', mane: 'Fuchsia', tail: 'Fuchsia', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'SaddleBrown', mane: 'Gainsboro', tail: 'Gainsboro', shoes: 'DarkSlateGrey', eye: 'AliceBlue' },
        { color: 'Khaki', mane: 'GhostWhite', tail: 'GhostWhite', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'LavenderBlush', mane: 'HotPink', tail: 'HotPink', shoes: 'DarkSlateGrey', eye: 'Aquamarine', unicorn: 'GoldenRod' },
        { color: 'PaleGoldenRod', mane: 'GoldenRod', tail: 'GoldenRod', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkSlateBlue', mane: 'Gray', tail: 'Gray', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'LemonChiffon', mane: 'Green', tail: 'Green', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'SlateGrey', mane: 'Grey', tail: 'Grey', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'LightSkyBlue', mane: 'HoneyDew', tail: 'HoneyDew', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'BlanchedAlmond', mane: 'HotPink', tail: 'HotPink', shoes: 'DarkSlateGrey', eye: 'Aquamarine', wings: 'GoldenRod' },
        { color: 'Thistle', mane: 'IndianRed', tail: 'IndianRed', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'CadetBlue', mane: 'Indigo', tail: 'Indigo', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'SandyBrown', mane: 'Khaki', tail: 'Khaki', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkTurquoise', mane: 'Lavender', tail: 'Lavender', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Moccasin', mane: 'Sienna', tail: 'Sienna', shoes: 'DarkSlateGrey', eye: 'Grey', wings: 'GoldenRod'  },
        { color: 'LightSlateGrey', mane: 'LemonChiffon', tail: 'LemonChiffon', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkSlateGrey', mane: 'LightBlue', tail: 'LightBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'OrangeRed', mane: 'LightCyan', tail: 'LightCyan', shoes: 'DarkSlateGrey', eye: 'Aquamarine', unicorn: 'GoldenRod' },
        { color: 'Crimson', mane: 'LightGoldenRodYellow', tail: 'LightGoldenRodYellow', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'MediumSlateBlue', mane: 'LightGray', tail: 'LightGray', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'OliveDrab', mane: 'LightGreen', tail: 'LightGreen', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkOrchid', mane: 'LightGrey', tail: 'LightGrey', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'RoyalBlue', mane: 'LightSalmon', tail: 'LightSalmon', shoes: 'DarkSlateGrey', eye: 'AliceBlue' },
        { color: 'PaleGreen', mane: 'LightSeaGreen', tail: 'LightSeaGreen', shoes: 'DarkSlateGrey', eye: 'Plum', wings: 'GoldenRod' },
        { color: 'Snow', mane: 'DarkSlateGrey', tail: 'DarkSlateGrey', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkGrey', mane: 'LightSlateGray', tail: 'LightSlateGray', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Teal', mane: 'LightSlateGrey', tail: 'LightSlateGrey', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'HoneyDew', mane: 'LightSteelBlue', tail: 'LightSteelBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'FloralWhite', mane: 'Violet', tail: 'Violet', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'SteelBlue', mane: 'Lime', tail: 'Lime', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'RosyBrown', mane: 'Linen', tail: 'Linen', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Chocolate', mane: 'Magenta', tail: 'Magenta', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'LightSeaGreen', mane: 'MediumBlue', tail: 'MediumBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Silver', mane: 'MediumOrchid', tail: 'MediumOrchid', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'LightGrey', mane: 'MediumPurple', tail: 'MediumPurple', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'LightSalmon', mane: 'MediumSpringGreen', tail: 'MediumSpringGreen', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Violet', mane: 'MediumTurquoise', tail: 'MediumTurquoise', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'SlateBlue', mane: 'MediumVioletRed', tail: 'MediumVioletRed', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'MistyRose', mane: 'MintCream', tail: 'MintCream', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkGoldenRod', mane: 'Moccasin', tail: 'Moccasin', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'MediumSpringGreen', mane: 'NavajoWhite', tail: 'NavajoWhite', shoes: 'DarkSlateGrey', eye: 'Aquamarine', unicorn: 'GoldenRod' },
        { color: 'BurlyWood', mane: 'Navy', tail: 'Navy', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'LightGray', mane: 'OldLace', tail: 'OldLace', shoes: 'DarkSlateGrey', eye: 'HotPink', wings: 'PowderBlue' },
        { color: 'MediumPurple', mane: 'OliveDrab', tail: 'OliveDrab', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Brown', mane: 'Orchid', tail: 'Orchid', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'MintCream', mane: 'PaleGreen', tail: 'PaleGreen', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'SlateGray', mane: 'PaleTurquoise', tail: 'PaleTurquoise', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Lavender', mane: 'PaleVioletRed', tail: 'PaleVioletRed', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'PapayaWhip', mane: 'PeachPuff', tail: 'PeachPuff', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Navy', mane: 'Peru', tail: 'Peru', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Maroon', mane: 'Pink', tail: 'Pink', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Tan', mane: 'Plum', tail: 'Plum', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkViolet', mane: 'PowderBlue', tail: 'PowderBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine', unicorn: 'GoldenRod' },
        { color: 'LightBlue', mane: 'Purple', tail: 'Purple', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkOrange', mane: 'RebeccaPurple', tail: 'RebeccaPurple', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'DarkBlue', mane: 'RosyBrown', tail: 'RosyBrown', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'SeaShell', mane: 'RoyalBlue', tail: 'RoyalBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Plum', mane: 'SaddleBrown', tail: 'SaddleBrown', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Linen', mane: 'Salmon', tail: 'Salmon', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'HotPink', mane: 'Sienna', tail: 'Sienna', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'WhiteSmoke', mane: 'Silver', tail: 'Silver', shoes: 'DarkSlateGrey', eye: 'Aquamarine', unicorn: 'GoldenRod', wings: 'LightSteelBlue' },
        { color: 'Bisque', mane: 'SlateBlue', tail: 'SlateBlue', shoes: 'DarkSlateGrey', eye: 'Aquamarine' },
        { color: 'Beige', mane: 'SlateGray', tail: 'SlateGray', shoes: 'DarkSlateGrey', eye: 'Aquamarine' }
    ]
}